apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  PG_USER_EMAIL: c29wb3J0ZTIzQGFkaWMuY29tLm14
  #soporte23@adic.com.mx
  
  DB_PASSWORD: U29wb3J0ZTIwMjM=
  # Soporte2023
  